<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>DpaaControl</AssemblyName>
    <Description>Пульт управления акустической ЦАФАР</Description>
    <BuiltInComAssemblyInteropEnabled>false</BuiltInComAssemblyInteropEnabled>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.22" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dpaa.Core\Dpaa.Core.csproj" />
  </ItemGroup>
</Project>
